server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Esto permite que React Router funcione correctamente
        try_files $uri $uri/ /index.html;
    }
}